/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MyBio: typeof import('./src/components/MyBio.vue')['default']
    MyInfo: typeof import('./src/components/MyInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpaceMan: typeof import('./src/components/SpaceMan.vue')['default']
  }
}
